#!/bin/bash
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Proses... " && sleep 30
echo "Finish...."
